# Generated by Django 3.2 on 2023-07-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='image',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='image_url',
        ),
    ]
