# Generated by Django 3.2 on 2023-07-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_auto_20230704_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='rating',
        ),
    ]
